"""update name and id

Revision ID: 8366da335489
Revises: fc800c011c73
Create Date: 2026-03-14 02:25:21.398076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8366da335489'
down_revision: Union[str, Sequence[str], None] = 'fc800c011c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('redirecturls', 'redirect_urls')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('redirect_urls', 'redirecturls')
    # ### end Alembic commands ###
