services:
  redis:
    image: redis:8.2.3-alpine3.22
    container_name: ${REDIS_CONTAINER_NAME}
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    command: >
      redis-server
      --requirepass "${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      start_period: 5s
      interval: 5s
      timeout: 3s
      retries: 10
    restart: always
    networks:
      - default_network

  postgres:
    image: postgres:17.6-alpine3.22
    container_name: ${POSTGRES_CONTAINER_NAME}
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}", "-q"]
      start_period: 5s
      interval: 5s
      timeout: 3s
      retries: 10
    restart: always
    networks:
      - default_network

  rabbitmq:
    image: rabbitmq:4.2.3-management-alpine
    container_name: ${RABBITMQ_CONTAINER_NAME}
    env_file:
      - .env
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      start_period: 5s
      interval: 5s
      timeout: 3s
      retries: 10
    restart: always
    networks:
      - default_network

  clickhouse:
    image: clickhouse/clickhouse-server:25.12.5.44-alpine
    container_name: ${CLICKHOUSE_CONTAINER_NAME}
    env_file:
      - .env
    ports:
      - ${CLICKHOUSE_PORT}:8123
      - ${CLICKHOUSE_NATIVE_PORT}:9000
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      start_period: 5s
      interval: 5s
      timeout: 3s
      retries: 10
    restart: always
    networks:
      - default_network
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  clickhouse_data:

networks:
  default_network:
    driver: bridge
